### ISSUE TITLE
Crystal Chest

### ISSUE THREAD

**Issue by UnlimatedStone9** [T145/metalchests#10]
Crystal Chests for some odd reason do not retain their inventory and instead re-add items to the players inventory if they open the chest again, however if a player doesn't re-open the GUI and starts messing around with items in their inventory they get permanently deleted and you're stuck with a chest that refuses to hold anything

Forge : 14.23.4.2739
Metal Chests : 1.2.2

**Comment by T145** [comment]
The Crystal Chest is being removed in later versions in favor of the explicit "metal" theme. There will be other larger metal chests, as well as better minecart upgrades and configurable inventory sizes.

Does this happen w/ any other chests? My guess is that it's a client-server desync issue.
