### ISSUE TITLE
In-world Chest Crash After Changing Chest Size in the Config

### ISSUE THREAD

**Issue by WenXin20** [T145/metalchests#101]
## Problem Details

- I got this crash after changing the config file for the diamond chest to 7x18. It was a bit odd since the previous diamond chest I had opened had not crashed.
- [Crash Log](https://paste.dimdev.org/ozocuweruw.mccrash)

## Environment

-   OS:  Windows 10
-   Full Forge version:  v14.23.5.2838
-   Mod version:  v6.0.1

**Comment by T145** [comment]
Was this a normal metal chest, or one of the mod support chests?

**Comment by WenXin20** [comment]
It was a normal diamond chest.

**Comment by T145** [comment]
@WenXin20 Upon the next mod update, this problem should be fixed after testing things myself. However, every time you change the JSON config significantly (i.e. any property that involves inventory size), you'll need to toggle `forceDataFixing` in the config. More info is included above that property.

**Comment by WenXin20** [comment]
Alright, thanks.
