### ISSUE TITLE
"WE BE RUNNING!"

### ISSUE THREAD

**Issue by duely** [T145/metalchests#102]
![](https://i.imgur.com/pc4nkCp.png)

Why is this a thing? I actually use my server console to pay attention to things.

**Comment by T145** [comment]
Ah, it's just a lingering debug statement left by accident. It really shouldn't spam that much though, unless you have a lot of metal chests in your world. Did the logging eventually terminate, or just keep running?

**Comment by Foxgreat** [comment]
Its terminating after few minutes after launch. But on start-up it spams on console alot. I have 6 servers with your mod with different mod packs by my build and it spams in each.

**Comment by T145** [comment]
@Foxgreat This issue is resolved in the latest release, so dw! Good to know it isn't infinite spam though, as it shouldn't be regardless.
