### ISSUE TITLE
Chest GUI Slots Arrangement

### ISSUE THREAD

**Issue by Seraphaestus** [T145/metalchests#103]
## Problem Details

Metal Chests' GUI inventory slots are arranged with a width of 16 slots per row, as opposed to vanilla Minecraft's 9 slots per row. 

Before updating the mod, we recall the smaller chests (e.g. Gold) having the 9 slots per row standard, and only the largest metal chests having higher numbers of slots per row, which is reasonable for screen space purposes. 

The reason we find it a problem is that it's jarring and harder to parse and organise with the 16 slots per row. 

A possible solution would be to have the slots per row for a given tier of metal chest as a config option. 

## Environment

-   OS: Windows
-   Full Forge version: 14.23.5.2838 (1.12.2)
-   Mod version: v6.1.0+mc1.12.2

**Comment by T145** [comment]
You can change how many slots are on each row by changing the number of columns in the JSON config. Changing the inventory size is already possible.
