### ISSUE TITLE
Metal Chests Stay Open

### ISSUE THREAD

**Issue by Velocihater** [T145/metalchests#105]
When you use them too much, they don't close and stay open

![2019-08-07_18 46 39](https://user-images.githubusercontent.com/40730042/62673717-211e9a80-b965-11e9-9f3f-196854a931a3.png)

![2019-08-07_16 28 48](https://user-images.githubusercontent.com/40730042/62673823-76f34280-b965-11e9-9994-7ada100cab2b.png)

-   OS: Windows 10
-   Full Forge version: 1.12.2 - 14.23.5.2838
-   Mod version: 6.1.0

**Comment by T145** [comment]
This is just a persistent problem in Minecraft. It can happen with any chest.
