### ISSUE TITLE
Copper Chest not being loaded when other mods add copper alongside Thermal Foundation

### ISSUE THREAD

**Issue by Velocihater** [T145/metalchests#106]
Whenever you have Thermal Foundation along with having Draconic or Ender.IO, the copper chest won't load and the mod won't recognize it upon loading up. I tested this without those 2 mods, and it's definitely them.

    OS: Windows 10
    Full Forge version: 1.12.2 - 14.23.5.2847
    Mod version: 6.1.0

**Comment by T145** [comment]
Does this persist even if you force the copper chest to be enabled from the JSON config? Part of the reason that's a feature is for situations like this.

**Comment by Velocihater** [comment]
![2019-09-15_20 34 31](https://user-images.githubusercontent.com/40730042/64930651-60f45f80-d7f8-11e9-9a3f-4851a055585a.png)
![2019-09-15_20 34 42](https://user-images.githubusercontent.com/40730042/64930652-62258c80-d7f8-11e9-8122-6870cccf9e01.png)
it still doesn't work when i enable it

**Comment by T145** [comment]
Is the copper chest the only one being affected?

**Comment by Velocihater** [comment]
Just copper, are there any other modded material chests? Silver seems to be registered

On Sep 16, 2019, at 6:08 AM, T145 <notifications@github.com<mailto:notifications@github.com>> wrote:


Is the copper chest the only one being affected?

**Comment by T145** [comment]
Does reverting the Forge version back to the one the mod is built upon fix this problem? If so then it's a Forge issue somehow that I either need to document and report, find a work-around for or do the first and wait on patches / submit a patch myself. Built version is here: https://github.com/T145/metalchests/blob/master/gradle.properties#L10

**Comment by Velocihater** [comment]
![2019-09-17_21 32 58](https://user-images.githubusercontent.com/40730042/65103137-ea3f9980-d992-11e9-8876-292d4ce84cd7.png)

Tried it on 2838, still broken

**Comment by Samrel556** [comment]
It seems that its actually the item render is broken. They can exist in the world if you pull one out of JEI

**Comment by Lord-Zarnox** [comment]
Having the same problem, and also noticed that there is no crafting recipe.

**Comment by T145** [comment]
Closing this issue to bundle alongside #114
