### ISSUE TITLE
[1.12.2-6.1.0] Empty strings are replaced with "==" using CustomMainMenu

### ISSUE THREAD

**Issue by Compegen** [T145/metalchests#107]
## Problem Details
When using a mod like Custom Main Menu, buttons without text will be filled with "==".
I also noticed this affecting the tooltips for Apotheosis' enchanted books, which have a line break in them normally.

Does not happen if string contains any characters.

## Screenshots
I made the text from Singleplayer, Multiplayer, and Mods empty. Refresh button is normally empty. 
![2019-09-15_11 27 51](https://user-images.githubusercontent.com/8009507/64924594-0a613400-d7ac-11e9-8978-2493688f8b61.png)

## Environment
-   OS: Win 10 Pro
-   Full Forge version: 1.12.2 - 14.23.5.2847
-   Mod version: 1.12.2 - 6.1.0

**Comment by T145** [comment]
How is this supposed to relate to MetalChests? Have you tried just deleting the `config` directory and launching w/ only CustomMainMenu & MC + any deps?

**Comment by Compegen** [comment]
In a fresh instance with only `CustomMainMenu`, `TBone`, and `MetalChests` installed, this issue happens. With only `TBone` and `CustomMainMenu` installed, this issue does not appear.

**Comment by Compegen** [comment]
This also affects Apotheosis' book descriptions
![2019-09-15_12 10 42](https://user-images.githubusercontent.com/8009507/64925153-105a1380-d7b2-11e9-8f59-1f1b31ec29cf.png)

**Comment by Velocihater** [comment]
the == happens on to my tooltips as well for some reason

**Comment by quat1024** [comment]
Here's the cause: https://github.com/T145/metalchests/blob/dabbb1570521d14afb072e065bd3a5f0d78b7b61/src/main/resources/assets/metalchests/lang/en_us.lang#L36

The first `=` is being parsed as a separator between the lang key and the value, so you have an "empty string" to "==" mapping. If you'd like to make a separator, starting a line with the `#` character makes it into a proper comment.
