### ISSUE TITLE
Forestry copper

### ISSUE THREAD

**Issue by KokSaker** [T145/metalchests#108]
## Problem Details

The Metal Chests mod doesn't recognize Forestry mod copper ingots for its chests.

## Environment

-   OS: Windows 10
-   Full Forge version: 14.23.5.2847
-   Mod version: v6.1.0

**Comment by KokSaker** [comment]
This might be related to this issue - https://github.com/T145/metalchests/issues/106
I also get the checkered texture if I forcefully enable the copper chest.

**Comment by T145** [comment]
Then it is. I guess it's safe to assume any mod that adds copper is having troubles then.
