### ISSUE TITLE
[1.12.2] Crystal Chest Problems

### ISSUE THREAD

**Issue by TheSnowyChickens** [T145/metalchests#11]
VanillaFix give me some errors. I just put some chests (from MetalChests) into the crystal chest.
This problem only occures with the crystal chest, in other chests I dont get this message.
Log - link is under the screenshots.^^

### Expected Behavior
No errors from VanillaFix.

### Actual Behavior
Errors from VanillaFix

### Steps to Reproduce (including precondition)
Install VanillaFix and your mod and put some chests into the crystal chest.

### Screenshot of this Problem
![2018-08-05_18 03 54](https://user-images.githubusercontent.com/29357962/43687688-fab212b6-98d9-11e8-9fc8-74caef067773.png)

![2018-08-05_18 04 56](https://user-images.githubusercontent.com/29357962/43687694-13203198-98da-11e8-98f5-0bd6a5493bf3.png)

Log: https://paste.dimdev.org/kinuhamebe.mccrash

### Your Environment

- OS: Win10 64bit
- Full Forge version: 14.23.4.2747
- Mod version: "v1.2.2.g3d3d54b" (v1.2.2)
- plus more mods (Modlist is in the log)

**Comment by T145** [comment]
Check out this: [https://minecraft.curseforge.com/projects/metalchests/files/2598609](https://minecraft.curseforge.com/projects/metalchests/files/2598609)
Enjoy!
