### ISSUE TITLE
Chests Out-Of-Order Compared To Config?

### ISSUE THREAD

**Issue by IdrisQe** [T145/metalchests#110]
Environment: Metalchests v6.1.0, Forge 14.23.5.2847
I have ABSOLUTELY zero idea how this happened. I was playing the game earlier, and went to upgrade my Iron Chest to the next tier up. I checked in JEI, and the next tier was Gold, so I crafted the Iron to Gold upgrade, applied it, all good. I remember noting that it was odd how Silver came AFTER Gold instead of the other way around. I did not manually edit the config at all.

My mod setup did change a little since then, but nothing added new ores, or removed existing ores, so nothing should have altered the config or anything, but when I went to play a few minutes ago, I suddenly find that the upgrade path is Iron>Silver>Gold. This is absolutely insane and driving me insane, I KNOW what I saw, and I KNOW I crafted Iron>Gold upgrade with no silver involved at all, but here I am now, with Silver in between the steps?! I didn't upgrade the mod version, so the config shouldn't have regenerated or anything.

Upon checking the config, even weirder, it still shows the old values:
`"chests": {
    "copper": {
      "index": 0,
      "enabled": "auto",
      "rows": 5,
      "cols": 9,
      "holding": 1
    },
    "iron": {
      "index": 0,
      "enabled": true,
      "rows": 6,
      "cols": 9,
      "holding": 1
    },
    "silver": {
      "index": 2,
      "enabled": "auto",
      "rows": 6,
      "cols": 12,
      "holding": 2
    },
    "gold": {
      "index": 1,
      "enabled": true,
      "rows": 5,
      "cols": 16,
      "holding": 2
    },
    "diamond": {
      "index": 2,
      "enabled": true,
      "rows": 6,
      "cols": 18,
      "holding": 3
    },
    "obsidian": {
      "index": 3,
      "enabled": true,
      "rows": 6,
      "cols": 18,
      "holding": 4
    }
  }`
It's like when it loaded this time, the mod just decided to not check the config and load the chests out-of-order. I'm utterly stumped. This says Silver should still be after Gold, yeah? (Which, by the way, is a really weird default config, and backed up by the slot difference being swapped. I didn't alter the JSON file at all, note.) Meanwhile, ingame, the order is reversed.

**Comment by T145** [comment]
This is likely due to an interaction while loading other mods. I'd just change all `"auto"` values to `true`, so that the variants are forcibly enabled, and then altering the indices to reflect your desired order.
