### ISSUE TITLE
Green space when using too many rows

### ISSUE THREAD

**Issue by aaronhowser1** [T145/metalchests#116]
## Problem Details

```
    "diamond": {
      "index": 2,
      "enabled": true,
      "rows": 12,
      "cols": 9,
      "holding": 3
    }
```

## Screenshots
![image](https://user-images.githubusercontent.com/15698722/86438752-cc96b300-bccc-11ea-8579-e7791686a45b.png)

## Environment

-   OS: W10
-   Full Forge version: 1.12.2-14.23.5.2847
-   Mod version: MetalChests-v6.1.0+mc1.12.2

**Comment by T145** [comment]
https://github.com/T145/metal-chests/blob/c31e660f99f8245301b85608fdaaba75fd4fb3bf/src/main/java/t145/metalchests/core/MetalChests.java#L130
