### ISSUE TITLE
[1.12.2] Vanilla rotation support (CarryOn)

### ISSUE THREAD

**Issue by TheSnowyChickens** [T145/metalchests#12]
The easiest way to describe it. :=)
Under my post you can see 1 comment from the Carry On developer.

https://github.com/Tschipp/CarryOn/issues/124#issuecomment-410604525

### Expected Behavior
Correct side from the lock, after end of carrying.

### Actual Behavior
It noted the lock side and dont rotate to the new placed side.

### Steps to Reproduce (including precondition)
Place the chest -> use carry on -> place the chest on a other block.

### Your Environment

- OS: Win10 64bit
- Full Forge version: 1.12.2 - 14.23.4.2747
- Mod version: v2.0.0

Also "Chest transporter" dont support your mod and I always open a issue for the support on their Github.

**Comment by T145** [comment]
The way I handle rotation right now is by remembering the direction in the TileEntity. Admittedly it's a force of a habit. The benefit to doing so is that I can avoid having to mess w/ the block's base metadata, and just it be used for different block variants. I'll see if I can come up w/ something.

**Comment by T145** [comment]
So the CarryOn developer is going to implement the usage of the `rotateBlock` method in block classes, which should work for a variety of mods. I've finished the implementation so MetalChests should now work on his next release.

**Comment by TheSnowyChickens** [comment]
Good job.
Thank you!

**Comment by T145** [comment]
@TheSnowyChickens Added ChestTransporter support, so no need for that issue.
