### ISSUE TITLE
[1.12.2] Minecarts

### ISSUE THREAD

**Issue by TheSnowyChickens** [T145/metalchests#15]
Some easy stuff:
- wrong TOP name info
- Item z-fighting (I hope this is the right feature/thing/name :D )

### Steps to Reproduce (including precondition)
Look at a Minecart and hold the Item in the hand an move the cam.

### Screenshot of this Problem
The 3 red arrows shows the 3 points of z-fighting
![2018-08-13_04 08 36](https://user-images.githubusercontent.com/29357962/44009899-4c58f7e4-9eaf-11e8-9569-8e3b354dc31b.png)

![2018-08-13_04 09 00](https://user-images.githubusercontent.com/29357962/44009846-e37f0128-9eae-11e8-83ac-2aa113733fb9.png)

### Your Environment
- OS: Win10
- Full Forge version: 1.12.2 - 14.23.4.2749
- Mod version: MetalChests-v2.3.9.gb92ee2f
- Theoneprobe-1.12-1.4.23

(Yes, Optifine is installed, but I have the same fighting bug with the tinkers axe without Opti)

**Comment by Boundarybreaker** [comment]
Can you double-check if it happens the on the chest cart item without optifine? The tinkers axe z-fighting is because of a different system it uses to generate textures which metalchests doesn't use.

**Comment by TheSnowyChickens** [comment]
Jep, with no Opti the same 3 pixels has the fighting.

![2018-08-13_04 47 29](https://user-images.githubusercontent.com/29357962/44010644-fffe0a74-9eb3-11e8-8706-750c8cc56b68.png)

**Comment by T145** [comment]
That's normal for minecarts, yes. Just fixed the name display for minecart entities.
