### ISSUE TITLE
Server Crash on startup

### ISSUE THREAD

**Issue by KorDum** [T145/metalchests#17]
### Expected Behavior

Server is starting.

### Actual Behavior

Server crash on startup (without Thaumcraft)
https://gist.github.com/KorDum/8ddd10721b0b0dc4534e468f6708ee10

### Your Environment

- OS: SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
- Full Forge version: 1.12.2-14.23.4.2750
- Mod version: 2.5.3.g03c118f

**Comment by T145** [comment]
Turns out good ol' Azzy forgot to include the golem parts API in the total Thaumcaft API package. I'll see if I can't decompile it.

**Comment by T145** [comment]
The latest version of the TC API is on MinecraftForums for whatever reason

[https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292130-thaumcraft-6-1-beta13](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292130-thaumcraft-6-1-beta13)

**Comment by KorDum** [comment]
Just in case. I don't use Thaumcraft in my modpack.

**Comment by T145** [comment]
The latest version (v2.5.7) should fix everything! I tested it in an instance where the latest version of Forge was installed, along w/ only MetalChests. Thanks for the prompt report!

**Comment by KorDum** [comment]
Thanks for fast fix!
