### ISSUE TITLE
Configurable Upgrade Paths

### ISSUE THREAD

**Issue by Divineaspect** [T145/metalchests#19]
What we are thinking of was being able to set materials, size per material, and what upgrades can apply to each material. 
For our purposes we can have wood >copper >gold>diamond>obsidian as a path as well as wood >iron>steel>obsidian for people who have gotten that far in our tech progression.
It will also help us establish that bronze and iron are equivalent mechanically save for rarity by being able to add bronze chests and set them to the same size as iron chests.

**Comment by T145** [comment]
What you want apart from adding new chest variants would be done automatically if silver were missing. But I'm guessing you want to keep it around for some reason. Let me make a little checklist:
- [ ] Let the automatic variant management be manually configurable
- [ ] Add bronze variant
- [ ] Add steel variant

I'll probably end up just creating another block called `BlockAlloyChest.java` that can hold all of the alloy variants. Splitting it up into two blocks is more than likely mandatory given how many metals and alloys can be floating around out there, and thus requires manual progression configuration regardless.

My thought; add a JSON config to the mod config directory for this purpose, and parse all entries as the enum definitions. Any syntax errors will logged under the mod's logger.

**Comment by Divineaspect** [comment]
For us Silver is a magical material.

If you're adding variants (for some reason I thought it was automagically generated) we'd also like a magical wooden chest and thaumium.

**Comment by Divineaspect** [comment]
Can we get the ability to set upgrade paths, or is that what that is, with index being steps along that path?

**Comment by T145** [comment]
`index` being its order, like copper first, iron second etc. Thaumium I can do since it fits the theme of the mod, but a "magical wooden chest" just sounds like a Hungry Chest to me honestly.

**Comment by Divineaspect** [comment]
Can we get the ability to set upgrade paths, or is that what that is, with index being steps along that path?

**Comment by T145** [comment]
*references prior comment*
In short yes.

**Comment by Divineaspect** [comment]
So like could both iron chest and bronze chest upgrade to silver or gold directly?
