### ISSUE TITLE
Quark Button Bug/Integration

### ISSUE THREAD

**Issue by sdaddy** [T145/metalchests#2]
### Expected Behavior

Buttons should appear beside MetalChests inventory.

### Actual Behavior

No buttons appear.

### Steps to Reproduce (including precondition)

Use Quark r1.4-122 with MetalChests v1.2.2.g3d3d54b.

### Screenshot of this Problem

N/A

### Your Environment

- OS: Windows 10 Pro x64
- Minecraft version: 1.12.2
- MetalChests version: v1.2.2.g3d3d54b
- Forge Version: 1.12.2-14.23.2.2624

**Comment by Boundarybreaker** [comment]
IIRC, many containers need to be manually added to the quark chest button list; otherwise inventories like crates and stuff won't appear.

**Comment by T145** [comment]
Apparently Vazkii doesn't have support for IItemHandlers (the standard amongst the MMD community) yet. I'll leave in my API support so that if he or someone else ever adds in the compatibility my containers will work out of the box.
