### ISSUE TITLE
Minecarts with Metal Chests don't interact with Hoppers

### ISSUE THREAD

**Issue by angelnc1989** [T145/metalchests#21]
### Expected Behavior
Hoppers push items into and from Minecarts with Metal Chest

### Actual Behavior
Hoppers don't interact with Minecarts with Metal Chests

### Steps to Reproduce (including precondition)
1. Place a rail on a hopper.
2. Place a Minecart with Metal Chest on the rail
3. Put items in the Minecart with Metal Chest

### Your Environment

- OS: Windows 10
- Full Forge version: 14.23.4.2750, Minecraft 1.12.2
- Mod version: 2.5.7

**Comment by T145** [comment]
Confirmed issue. Working on a fix.
