### ISSUE TITLE
Can't properly shift-click into the inventory of Minecarts with Metal Chests

### ISSUE THREAD

**Issue by angelnc1989** [T145/metalchests#22]
### Expected Behavior
Minecarts with Metal Chests drop their content when broken

### Actual Behavior
Minecarts with Metal Chests don't drop their content when broken and the items are deleted.

### Steps to Reproduce (including precondition)
1. Place a Minecart with Metal Chest on a rail.
2. Put some items in it.
3. Break the Minecart with Metal Chest.

### Your Environment
OS: Windows 10
Full Forge version: 14.23.4.2750, Minecraft 1.12.2
Mod version: 2.5.7

**Comment by T145** [comment]
In survival mode they drop items for me. I'm using Forge `1.12.2-14.23.4.2747`. Admittedly one thing I did find is that I was unable to shift right-click a stack into the cart inventory, which definitely needs to be fixed. Do you have a list of mods you're playing with? Maybe it's an interaction w/ some other mod.

**Comment by angelnc1989** [comment]
The shift-rightclick issue only seems to be happening with the Copper, Iron and Silver variant. Gold, Diamond and Obsidian works for me.

The items not dropping was a mistake of mine. They drop just fine. Sorry.

**Comment by T145** [comment]
@angelnc1989 https://minecraft.curseforge.com/projects/metalchests/files/2604867
Enjoy!
