### ISSUE TITLE
[Bug] Sorting metal chest lid stuck open

### ISSUE THREAD

**Issue by Akitori** [T145/metalchests#27]
### Expected Behavior

Close Sorting Chests, send items to it via hopper/filter, expect its lid to stay closed

### Actual Behavior

Lid stays up until reloaded/replaced

### Steps to Reproduce (including precondition)

Setup a filter using the sorting system.
Send item to the system.
Open chest once.
Lid remains open forever

### Your Environment

- OS: Windows 10
- Full Forge version: 1.12.2-14.23.4.2747
- Mod version: v3.0.5.ge3381ce

**Comment by T145** [comment]
Is this a recurring problem or occurring on a server? In my single player world it works just fine. I have a sorting metal chest connected to a sorting chest, set a filter on the sorting iron chest for all ores, place ores in the sorting chest and test the iron sorting chest. The lid doesn't remain open.

**Comment by Akitori** [comment]
Its a recurring problem. I'm using the filter that checks the inventory. I was using potions, and yeah, that happened. I can probably record it if need be.

**Comment by T145** [comment]
If you could record it that would be great. Specifics help me narrow down the problem a lot faster.

**Comment by T145** [comment]
Or some pictures at least so I can try to recreate it myself. B/c there was no prior mention of potions.

**Comment by Akitori** [comment]
uh....I found another bug while trying to replicate the bug. 

https://youtu.be/x088Bnk5QiQ

**Comment by T145** [comment]
Ok, so the original problem was that the lid was being stuck. This actually happens to vanilla chests too sometimes. If that happens ever again let me know. The other bug you've reported I can verify happens. I'll get to work on it. If you can post a new issue detailing this while I work on a fix that would be great!
