### ISSUE TITLE
Bug: Sorting Chests don't keep filter data/logic upon world reload

### ISSUE THREAD

**Issue by Akitori** [T145/metalchests#28]
### Expected Behavior

Leave world, come back in. Expect filters/things to work

### Actual Behavior
Logic doesn't update. The entire setup needs to be reset/replaced.

### Steps to Reproduce (including precondition)

Make a filter. Test it. Reload world. Done.

### Screenshot of this Problem

https://youtu.be/x088Bnk5QiQ

**Comment by T145** [comment]
Just out of curiosity, may you install IronChests alongside RR2 and see if the same bug happens w/ the Sorting Iron Chests?

**Comment by Akitori** [comment]
video for ya
https://youtu.be/f1fmGdkjREM

**Comment by T145** [comment]
Fixed. I'll upload the release shortly.

**Comment by T145** [comment]
Enjoy! https://minecraft.curseforge.com/projects/metalchests/files/2605966
