### ISSUE TITLE
[Suggestion] Project Table

### ISSUE THREAD

**Issue by LokyLive** [T145/metalchests#3]
Crafting Chest 

Hey i like Metalchest but i get an idea for you to make it more usefull than Ironchest mod

Could you add crafting table with metal upgrade ?

Like a copper version wich keep inventory, get an internal copper storage chest and upgradable for more internal storage ?

**Comment by T145** [comment]
Sounds a lot like a project table, or something similar to what Thermal Expansion does. If @Boundarybreaker is willing to cook up some block textures I'll add it in ASAP!

**Comment by Boundarybreaker** [comment]
Textures are made!

**Comment by LokyLive** [comment]
Hey guys when the next version will be updated ? still working on ?

**Comment by T145** [comment]
@LokyLive Development was suspended for a while b/c of me graduating. It shall resume soon!

**Comment by Jkosio23** [comment]
hmmmm, seems like this was dropped?

**Comment by T145** [comment]
Yes, but will be moved to it's own mod eventually. It's not technically a chest, so I didn't want to include it and over-saturate the mod.

**Comment by Jkosio23** [comment]
ahh, thanks for the info!
