### ISSUE TITLE
[Error] Failed to load tile entity Metal Chest

### ISSUE THREAD

**Issue by KorDum** [T145/metalchests#31]
### Actual Behavior

I updated mod from v3.0.2.g1652b57 to 3.1.6.g7177eac.
In the log errors are written after server startup:
https://gist.github.com/KorDum/70dbf289964faabe1658a8d5076aaa10

### Your Environment

- OS: SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
- Full Forge version: 1.12.2-14.23.4.2750
- Mod version: 3.1.6.g7177eac

**Comment by T145** [comment]
This is why I've encouraged world backups, and item migration to other inventories when upgrading from older versions. This is mentioned in the changelogs. Thank you for confirming the problem when going through that version transition!
