### ISSUE TITLE
[Quark] Adjust GUI textures to fit the Quark search bar

### ISSUE THREAD

**Issue by TimGoll** [T145/metalchests#32]
I'm ignoring your default form. I hope it is okay. You added quark support but the searchbar is too big in all your chests.

![2018-08-24_20 36 43](https://user-images.githubusercontent.com/13639408/44603676-b6bc2b00-a7e3-11e8-85b1-5c54cfb5a6a0.png)

**Comment by T145** [comment]
No, the upper part of the GUI is too thin. xd
I'm using the GUI textures from IronChests currently, but if @Boundarybreaker touches them up to compensate for that extra space, your problem will be solved.

**Comment by TimGoll** [comment]
okay. If @Boundarybreaker has no time to do it, I can do it too.

**Comment by T145** [comment]
Whatever you'd like to do. I don't mind either way.

**Comment by TheSnowyChickens** [comment]
Hi,
the problem with no chest and inventory name is connected to the IronChests GUI texture?
![ironchests gui](https://user-images.githubusercontent.com/29357962/44636359-af477e00-a9ab-11e8-92a5-c17131305e6c.png)

**Comment by T145** [comment]
Yes and no. IronChests never had the inv name space by default. The text is handled in code, but the available space is obviously from the texture.

**Comment by TheSnowyChickens** [comment]
Soo, you will add this feature in one of the next versions? :D 
(pls with anvil re-name support^^)

**Comment by T145** [comment]
@TheSnowyChickens Perhaps; I'd say anvil renaming should be a separate issue.

@TimGoll Have you been able to get on fixing the textures?

**Comment by TimGoll** [comment]
I was all ill but I think I have some time today!

**Comment by T145** [comment]
Sure that's fine.

**Comment by TimGoll** [comment]
Okay, I tried a few things and it shouldn't be a problem. Except for the diamond chest. 

Just as a reminder, the GUI looks like this.
![diamond_container](https://user-images.githubusercontent.com/13639408/44736819-867cd100-aaf0-11e8-8adc-4427ef6c2969.png)

Does anyone have an idea how to add a search bar to this without removing storage slots?

Currently there are 9*12=108 slots. I could change it to 8*13=104 or (if you want to squeeze it) 8*14= 112. Either way, the amount of slots chages. For compatiblity reasons, the latter one is better.

**Comment by T145** [comment]
That's fine. The container logic will need to be updated though.

**Comment by TimGoll** [comment]
So... what size should I go for?

**Comment by T145** [comment]
The latter option seems to be better, since dealing w/ even numbers is always easier.

**Comment by TimGoll** [comment]
okay. It looks a bit crowded though. But it should be okay. Or you add a scrolling bar. Shouldn't be too hard

**Comment by T145** [comment]
Closing this for now, since either Tim's PR or my dynamic GUIs will solve this at some point.
