### ISSUE TITLE
Proposed texture change to align with vanilla chests

### ISSUE THREAD

**Issue by phyne** [T145/metalchests#34]
Comparison
https://imgur.com/a/JfQOvjG (warning: image for ants ahead)

https://drive.google.com/open?id=1GMzDVkhK66Zc1vaaSSycoYVOp2X3p3ME

I edited it for myself but figured I'd drop this off here. It doesn't look like you can actually put anything into the chests without the black void being there!

**Comment by T145** [comment]
So what specifically did you change? And if you've updated them you can commit them to a fork and create a pull request to the main repository.

**Comment by TimGoll** [comment]
he made the inside of the chest black

**Comment by phyne** [comment]
I've never contributed on github before, I apologize. Yes I made the inside black. I'll try and do it the proper way as you suggested in a moment.

**Comment by TimGoll** [comment]
Go to the main page of the repo and press the fork button. Now you have to clone it to your PC. GitHub Desktop is the easiest way to do this. Now you have the files on your pc. Change the files you want to change and commit and push in GitHub desktop. If you now navigate to your forked repo you should see something like "1 commit ahead of...". Next to it is a "create pull request button. Do this and add a short description. If you add #34 to your text, a link to your pullrequest will appear in this issue thread.
