### ISSUE TITLE
With the improvement of a double wooden chest, upper half of its contents are doubled

### ISSUE THREAD

**Issue by Bulldog83** [T145/metalchests#39]
## Error Details

I've upgraded a double wooden chest to iron chest, it wast full, and after that upper half of it's content was at once and in upgraded chest and in 2nd wooden chest.

## Environment

- Full Forge version: 14.23.4.2747
- Mod version: v3.1.6.g7177eac

**Comment by T145** [comment]
This issue has been confirmed. Should hopefully be resolved shortly. Basically what's happening is that the inventory between the chests is being shared. Since `IItemHandler`s don't have a `clone()` method I just need to create a new inventory object and pass that to the upgraded chest.
