### ISSUE TITLE
[BUG] Crystal Variants (chest & cart) do not show items when upgraded

### ISSUE THREAD

**Issue by T145** [T145/metalchests#4]
Seems to be that when using an upgrade item on a chest or cart going up to the crystal tier, the items do not render right away. The inventory needs to be updated by opening the inventory, and then everything works perfectly. Fixing this for the chest should also fix it for the cart naturally, as the cart maintains a copy of TileMetalChest.

**Comment by T145** [comment]
Here's a video demonstration of the bug!
**_MUTE AUDIO_**
[https://www.dropbox.com/s/kdtkzfsyihsltpj/2018-03-17%2023-20-00.flv?dl=0](https://www.dropbox.com/s/kdtkzfsyihsltpj/2018-03-17%2023-20-00.flv?dl=0)

**Comment by ArtixAllMighty** [comment]
Classic client / sevrer desync issue. 
Use the debugger and breakpoints to see when and where your inventory content gets set, and why it doesn't get updated.
