### ISSUE TITLE
[1.12.2] ? ? ? Minecarts

### ISSUE THREAD

**Issue by TheSnowyChickens** [T145/metalchests#42]
## Error Details

1. of your questions: Can't open the minecart with chest.
2. of your questions: I should can open it ?
3. of your questions: I can't
4. of your questions: I have only this: https://paste.dimdev.org/jupilakori.mccrash

## Screenshots
![2018-10-04_05 32 16](https://user-images.githubusercontent.com/29357962/46451506-fee14c80-c796-11e8-9daa-fad39b6ee0cf.png)
(I right click the minecart = the info in the top right corner)
(Yes, these minecarts are placed/spawned with 3.7.0, these are not 3.1.6 carts)
## Environment

- OS: Win10 (1803) 64bit
- Full Forge version: 1.12.2 - 14.23.4.2765
- Mod version: 3.7.0

PS: If you need more info, u need to wait ~7h, because I go to sleep now.

**Comment by T145** [comment]
What happens if you don't have VanillaFix installed? I'm assuming this is a world you've ported as well, which may explain some of the problems.

**Comment by T145** [comment]
To quote someone over at MMD:
```
Hobo JoeToday at 2:46 PM
It's not a problem with your source code, that exception cannot be thrown by something you can fix in your source
it's an issue with compilation
usually because of incorrect dependencies
```
