### ISSUE TITLE
[CRASH] Incompatible w/ the latest Thaumcraft due to its updated API

### ISSUE THREAD

**Issue by TimGoll** [T145/metalchests#43]
Forge version `forge-1.12.2-14.23.4.2757`

Game crashes on load with metalchest added. Same thing happens with the two neweset versions, I haven't tested an older version.

It's strange, that the last version of your mod worked for a while now and it suddenly changed. It seems to be a problem with thaumcraft, but reverting two an older version oc TC doesn't change anything. forge 66 doesn't work either, forge 68 is incompatible with immersive engineering and thaumcraft

[Crashreport](https://gist.github.com/TimGoll/491668208bd139665771ad514449323e)

Maybe I'm dumb and I made a mistake, but there seems to be a problem

**Comment by TimGoll** [comment]
okay, update: after some tinkering and forcing minecraft to use the newest version I can update the problem. Version 3.7.0 crashes on load, but version 3.16 works perfectly fine

**Comment by T145** [comment]
Issue confirmed. For now just stick w/ what's known to be compatible: https://github.com/T145/metalchests/tree/master/libs

**Comment by TimGoll** [comment]
See: https://github.com/BluSunrize/ImmersiveEngineering/issues/3241

**Comment by T145** [comment]
No the problem is on my end. The latest version of Forge provided more info in my crash log this time though, so I should be able to solve the issue.
