### ISSUE TITLE
Charset Chests Support

### ISSUE THREAD

**Issue by 8-BrickDMG** [T145/metalchests#44]
## Error Details

Hi,

I'm using Metal Chests and Charset Chests in a mod pack but noticed there isn't support between the two when using the chest upgrade items.

I'd like to be able to use the upgrades on the Charset chests without having to craft a new Metal Chest and then moving the items over.

Right clicking an upgrade on these chests doesn't result in a change.

Many thanks!

## Environment

- OS: Windows 10 (Client Side) & Debian 4.9.51-1 (Multiplayer Server)
- Full Forge version: MC 1.12.2, Forge 14.23.4.2756
- Mod version: MetalChests-v3.1.6.g7177eac.jar

**Comment by T145** [comment]
You can also ask Asie to add compatibility to Charset. There's a way for any mod dev to add compatibility to my upgrades. As follows:
```java
((ItemChestUpgrade) ItemsMC.CHEST_UPGRADE).addDefaultChest(myBlock);
```

**Comment by asiekierka** [comment]
@T145 Why don't you, instead, simply check if the item version of the chest is a valid chestWood?

**Comment by T145** [comment]
B/c I add handle more chest variants than just the normal upgrades. There are also the Hungry Chest upgrades to worry about. Oh and reference the README for better details on adding compatibility; the statement up there is before the formal API.

**Comment by asiekierka** [comment]
Perhaps you could still check the oredict entry and simply append to it?
