### ISSUE TITLE
[Suggestion] Some tweaks

### ISSUE THREAD

**Issue by DevTimur** [T145/metalchests#47]
1) Move config file from T145 folder into main Config folder, so it's easyer to find. Or atleast name this folder "Metal chests"
2.0) Hide chest variant if there is no supported metal (Copper and Silver if there is no mods with these metals)
 or
2.1) Add option to disable and hide any chest variant via config, including upgrade for this variant

Overall, i think this mod is better then Iron Chests, because there is no Shulker, and no "joke" dirt chest

**P.S. Don't mind 2.0, because i see you already aware of this problem**

**Comment by T145** [comment]
"`2.1`" has already been recommended. Reference the currently open issues.
