### ISSUE TITLE
[Suggestion] View items in specific slot

### ISSUE THREAD

**Issue by DevTimur** [T145/metalchests#48]
I got one thought... You dont have crystal chest, and this is actually your disadvantage.
Most usefull part of crystal chests is that you can see what's inside.
What if you make your own crystal chest, and it will show what's inside. But not everything, only specific slot. For example you add extra slot, player can place "ghost" item for a chest to show.
Metal ingot for metals chest, wooden log for wood chest, etc. I think it would be quite cool.

**Comment by T145** [comment]
There's something I'm working on to compensate for the crystal variant absence. Rest assured.

**Comment by T145** [comment]
To be more specific, the plan is to have a single crystal upgrade, allowing any chest to become a crystal version.
