### ISSUE TITLE
Major crashing Involving Creative mode

### ISSUE THREAD

**Issue by TacticalUniverse** [T145/metalchests#49]
## Error Details
https://paste.dimdev.org/rolunidiwa.mccrash

As soon as you click the metalchest pick in the creative menu it crashes you straight to the desktop

https://paste.dimdev.org/rolunidiwa.mccrash

## Environment

- OS: 
- Full Forge version:  1.12.2 forge 2772
- Mod version: 
V3.8.1

**Comment by T145** [comment]
Which chest did you pick? Does it happen to at least one of the same variety? What does your config file look like?

**Comment by TacticalUniverse** [comment]
It did it as soon as I clicked on the menu to get into seeing the chest

**Comment by T145** [comment]
I've been unable to recreate the error. Try changing your Forge version back to the recommended version and see what happens.

**Comment by TacticalUniverse** [comment]
kinda cant cause it will break my pack/server

**Comment by T145** [comment]
Which mods does doing so break?

**Comment by TacticalUniverse** [comment]
well I have 290 + mods in my pack so doing so may break things with the mods that have updated for forge 2772

**Comment by T145** [comment]
I've done some testing w/ the latest version of Forge, and can confirm that your crash does not happen w/ MetalChests and all of its supported mods installed on my system. My guess is that there's some mod in your pack that's editing some core function related to GUIs and it's causing the crash. If you can confirm that at least what I have on your system I can start narrowing down the culprits.

**Comment by TheSnowyChickens** [comment]
Hi,

I have still a crash with the creative inventory tab:

https://paste.dimdev.org/sawadutavo.mccrash

**Comment by T145** [comment]
Do you have minecarts disabled?

**Comment by TheSnowyChickens** [comment]
Yes

**Comment by T145** [comment]
Alright I know what the problem is.
