### ISSUE TITLE
Chest recipes not present when material present

### ISSUE THREAD

**Issue by terrapin47** [T145/metalchests#50]
-- Expected behavior
If I have materials for chests ( copper, silver, etc ) I should also have the recipes for those chests.

  -- Actual behavior
Even though properly oredicted materials exist, I only have vanilla material recipes available.  

  -- Detailed logs of the issue -->
I'm currently using Embers Rekindled for these materials, but I would expect that it just came from the oredict, so that any mod that added a proper material would work.  

I also have thaumcraft installed and don't seem to have any recipes for the hungry chests.  Not sure how those are supposed to work though, might not be a regular crafting recipe.

## Environment

- OS: Win10
- Full Forge version: 1.12.2 14.23.5.2768
- Mod version: v3.8.1.gfd0d85a

**Comment by T145** [comment]
Be sure the mods you're using actually add those ore values to the ore dictionary. I know Thermal Foundation and Base Metals add their ores to the dictionary, so having either of those installed should remedy your issue. As for the hungry chest recipes, they do appear on my end. Try installing one of the previously mentioned mods and see if that fixes things.

**Comment by terrapin47** [comment]
As outlined in the original post, they do add the ore values into the ore dictionary.

To replicate, simply install Embers Rekindled and Metal Chests together.  Can add in CT if you want to observe that the oredict exists.

https://github.com/EpicSquid/Embers/blob/d9fda86b103e0c89b10ec99818157389afa8fba7/src/main/java/teamroots/embers/recipe/RecipeRegistry.java#L141

**Comment by T145** [comment]
Issue confirmed. Forge must have changed something w/ how the crafting factories work; I'll look into it.
