### ISSUE TITLE
Double chest not properly unlinked when one side is upgraded

### ISSUE THREAD

**Issue by lOmicronl** [T145/metalchests#52]
## Error Details

Replication steps:

Place down a vanilla double chest. Fill all six rows to the brim with cobblestone. Apply a wood-to-iron upgrade to one of the two sides of the double chest. Open both chests and look inside.

Expected result:

Wooden single chest contains three rows of cobblestone. Iron single chest contains three rows of cobblestone and three empty rows.

Actual result:

Wooden single chest contains three rows of cobblestone. Iron single chest contains six rows of cobblestone and no empty rows.

The three extra rows of cobblestone are real, persist through relogging, and can be taken out and used.

So is this a dupe bug? Nope. Upon taking something from the wooden chest and then looking into the iron chest, you'll see that the corresponding slot there is now also empty. This also works vice versa (taking from the iron chest results in empty slots in the wood chest). In other words, the upgrade does not properly unlink the double chest.

## Environment

- OS: Windows 10, latest patch level
- Full Forge version: Minecraft 1.12.2 on Forge 14.23.5.2768
- Mod version: v3.9.0

No other mods are required to reproduce.

**Comment by T145** [comment]
That's funny, b/c this bug popped up before and was fixed. Not quite sure what's up this time around.
