### ISSUE TITLE
Missing ore dictionary entries 

### ISSUE THREAD

**Issue by LemADEC** [T145/metalchests#54]
As of 3.9.0, chests are missing the generic 'chest' ore dictionary registration.
They do have their specific material variation registered, just missing the generic one also found in vanilla.

**Comment by T145** [comment]
Do you mean the ore dictionary entries aren't registered? Idk what you mean by "the generic 'chest' ore dictionary registration."

**Comment by LemADEC** [comment]
You can register the same item under multiple dictionary entries.
Currently, your chests are only registered in 'chestCopper', 'chestGold', etc.
They should also be registered in 'chest', which is the generic dictionary for all types of chests.
