### ISSUE TITLE
Recipe has no output. MetalChests metalchests:recipe_minecart_chest_copper 

### ISSUE THREAD

**Issue by TacticalUniverse** [T145/metalchests#56]
## Error Details

https://gist.github.com/TacticalUniverse/93bf773570eb250c63b4bb9c22585c57

## Environment

- OS:  Windows 10
- Full Forge version:  1.12.2(modded) forge-14.23.5.2796 
- Mod version:  3.0.9

**Comment by T145** [comment]
Closing this issue to centralize information, as the problems may be linked.
