### ISSUE TITLE
Inventory Tweaks chest buttons overlap chest slots

### ISSUE THREAD

**Issue by IronPiston** [T145/metalchests#57]
https://imgur.com/a/yFyJjxm

  -- Inventory tweaks buttons shouldn't overlap chest slots
  -- The buttons clip/cover slots on the far right, similarly to chests from Iron Chests
  -- Maybe each chest should say "Iron Chest" or "Gold Chest" at the top similar to vanilla chests to leave room for the buttons.

- OS: Fedora 29
- Full Forge version: 14.23.5.2808
- Mod version: 4.0.1

**Comment by T145** [comment]
The eventual plan is to have JSON configurable inventories, which will lead to dynamic GUI textures. This problem should be solved automatically when inventory names are displayed on top of the GUI, much like regular chests. I'll also add the feature to name the chests with name tags, and the updated names will appear in place of the default.
