### ISSUE TITLE
Abilities triggered by having specific items in the inventory

### ISSUE THREAD

**Issue by T145** [T145/metalchests#60]
The problem of Trapped Chests has yet to be addressed, and this is my take on the problem. Instead of having craftable Trapped Chest blocks (which just adds more blocks to the registry), I'll just add the ability to the chests that if they contain one stack of redstone or one block of redstone they automatically become trapped. This will mean their model texture will be updated to reflect the change. Another option would just be to add the ability to shift+right-click the block w/ redstone to make it trapped, and when the block is broken the redstone will be returned.

There are other options that can be added to slightly boost certain stats of a chest w/ this system as well. One I threw around was that for each block of obsidian in the inventory, its explosion resistance would be increased by 0.025%.

I'd love to hear more ideas and input from the community!

**Comment by IronPiston** [comment]
The main issue I see with using redstone inside the chest as a trigger to convert to a trapped chest is unintentional conversion. Someone could be storing redstone inside a chest, and accidentally shut off a nearby machine or a pipe by opening the chest. I think shift right clicking with a single redstone dust would be much cleaner and wouldn't lead to issues.

On the other hand, the obsidian inside a chest increasing blast resistance wouldn't cause issues, but I also couldn't think of a scenario where I'd find obsidian blast resistance insufficient. The idea of stored items passively buffing a chest is a neat idea though.

**Comment by T145** [comment]
I'll just stick to the shift-click, single redstone dust conversion.
