### ISSUE TITLE
Thaumcraft crafting issue

### ISSUE THREAD

**Issue by Danymaddox** [T145/metalchests#61]
## Problem Details

<-- Please detail the problem here, including:  -->
  -- Expected behavior  -->
Avaliable crafting recipes for copper chest and silver chest if there's any ingotCopper and ingotSilver registered in the oredict.
  -- Actual behavior  -->
There's no recipe for silver or copper chests (Thaumcraft versions doesnt have either)
  -- Detailed logs of the issue -->
No logs.

## Environment

- OS: Windows 64bits
- Full Forge version: Minecraft 1.12.2  and Forge: 14.23.5.2815
- Mod version: MetalChests-v4.0.1.g01955d6

**Comment by T145** [comment]
Thaumcraft and other unique mod support is being moved over to [https://github.com/T145/metalchests-compat](https://github.com/T145/metalchests-compat), so I'd post that over there once I publish a release and the issue persists.
