### ISSUE TITLE
Incompatiblility/Crash with Quark & Capabilities

### ISSUE THREAD

**Issue by WenXin20** [T145/metalchests#62]
## Problem Details

I got this crash with the newest Quark mod update while trying to load my world.

[Crash Report](https://paste.dimdev.org/adoqafozak.mccrash)
More details here: svenhjol/Charm#31.

- Full Forge version:  Forge v14.23.2825
- Mod versions: 
Metal Chests v4.0.1.g01955d6
AutoRegLib r1.3-27
Quark r1.5-147

**Comment by Hubry** [comment]
This isnt caused by this mod at all, it just happened to stand in the crossfire as it also has compat with Quark's dropoff handling.
