### ISSUE TITLE
[BUG] MutableBlockPos: Illegal Access Error on Start-up

### ISSUE THREAD

**Issue by TripOptic** [T145/metalchests#63]
Not sure what mod I updated but every time I launch the following log happens every time.

https://gist.github.com/TripOptic/7a510684d166a5a726ac078e0e6c136f

Environment

- OS: Windows 10  v1803
- Full Forge version: 1.12.2(modded) forge-14.23.5.2836
- Mod version:  MetalChests-v4.0.1.g01955d6.jar

Edit: I fixed the Gist link. I did not realize it did not work.

**Comment by T145** [comment]
There must be something in that list of mods that changes `MutableBlockPos`. For now I apply a simple fix.
