### ISSUE TITLE
[BUG] Crash when trying to handle other mods on startup

### ISSUE THREAD

**Issue by Warrock3280** [T145/metalchests#64]
The game crashes with last MetalChests version (4.6.6).
[Here's crashlog](https://gist.github.com/Warrock3280/7df5d83a10bd686b06ba34aa045a1fe6)
You can see `net/blay09/mods/refinedrelocation/ModBlocks`, but i even don't have Refined Relocation installed.

**Comment by WonderDog** [comment]
Similar crash here with version 4.6.6.

`java.lang.NoClassDefFoundError: vazkii/quark/decoration/block/BlockCustomChest` and there is no quark installed in this modpack

[Crashlog](https://gist.github.com/WonderDog/27aa69360bdff876c9b9b75b6e7274f9)

Rolling back to v4.0.1 fixes the issue.

**Comment by T145** [comment]
Sorry about that. Figured this issue was resolved already from previous commits.
