### ISSUE TITLE
[BUG] Crash upon attempt to apply Metal Chests to Cactus Mod's Cactus Boat

### ISSUE THREAD

**Issue by DWX12** [T145/metalchests#65]
## Problem Details

Tried using a boat from The Cactus Mod then crashed.

Crash Report: https://paste.dimdev.org/wukicifuzo.mccrash

## Environment

- OS: Windows 7
- Full Forge version: 5.2853
- Mod version: MetalChests-v4.6.9.g1f83dbf

**Comment by T145** [comment]
As far as I can see the mod doesn't have a boat. It does have a minecart though:
[https://minecraft.curseforge.com/projects/the-cactus-mod?gameCategorySlug=mc-mods&projectID=291433](https://minecraft.curseforge.com/projects/the-cactus-mod?gameCategorySlug=mc-mods&projectID=291433)

**Comment by T145** [comment]
Alright I guess it just isn't listed on CF for whatever reason: [https://github.com/Mrbysco/ModJNam-Mod/blob/master/src/main/java/com/Mrbysco/cactusmod/entities/EntityCactusBoat.java](https://github.com/Mrbysco/ModJNam-Mod/blob/master/src/main/java/com/Mrbysco/cactusmod/entities/EntityCactusBoat.java)

This only happens b/c the Cactus Mod doesn't simply set its boat type to something. I can add a failsafe for lazy devs.

**Comment by DWX12** [comment]
Thank you for taking a look into the issue and working to resolve it.
