### ISSUE TITLE
Crash when riding a boat added by Biomes O' Plenty

### ISSUE THREAD

**Issue by belathus** [T145/metalchests#69]
## Problem Details

Well, I obviously expect my client not to crash when I try to ride a boat. Specifically, I crafted a cherry blossom wood boat from Biomes O' Plenty and tried to ride it. When I did, my client immediately crashed.

https://gist.github.com/belathus/3c5d341d74ae238274e8abc640002a60

## Environment

- OS: Linux Mint
- Full Forge version: 1.12.2-14.23.5.2825
- Mod version: 4.6.9

**Comment by T145** [comment]
This problem was fixed back in #65

**Comment by belathus** [comment]
So it'll be fixed in the next release then? Mind you, I was not trying to put a metal chest in a boat.

**Comment by T145** [comment]
Well the error is the same, so I'll say yes for now.
