### ISSUE TITLE
Freshly upgraded chest doesn't close after opening.

### ISSUE THREAD

**Issue by rallias** [T145/metalchests#7]
When I apply a new upgrade to a chest, say the copper to iron upgrade, if I subsequently open the chest, it does not close when I exit the inventory.

### Expected Behavior

Chest should always close if nobody's in it.

### Actual Behavior

![2018-07-04_19 39 42](https://user-images.githubusercontent.com/1843506/42297078-3c5962fe-7fc2-11e8-946b-f56ecef89972.png)

### Steps to Reproduce (including precondition)

1. Apply upgrade (such as iron to silver upgrade) to chest.
2. Open chest.
3. Use `esc` to exit the chests inventory gui.
4. Observe failure to re-close.

### Screenshot of this Problem

![2018-07-04_19 39 42](https://user-images.githubusercontent.com/1843506/42297078-3c5962fe-7fc2-11e8-946b-f56ecef89972.png)

### Your Environment

- OS: Win 8.1
- Full Forge version: 1.12.2-14.23.4.2727
- Mod version: 1.2.2

**Comment by Boundarybreaker** [comment]
This is a pretty common desync issue that even vanilla chests have on servers, but if this is single-player too that might be worth taking a look at.

**Comment by rallias** [comment]
Yeah, that's single player.

I get that it's a common desync issue. However, the issue at hand was reproducible, hence the report.

**Comment by T145** [comment]
It's actually a pretty easy fix; I'll get on this.
