### ISSUE TITLE
4.9.2 - Startup Crash

### ISSUE THREAD

**Issue by HalestormXV** [T145/metalchests#70]
https://pastebin.com/qVu0epWQ

Seems to be a startup crash on 4.9.2. Reverting back one version resolves the crash.

**Comment by T145** [comment]
What does your config file look like?

**Comment by HalestormXV** [comment]
Sorry, missed the post. Configs are default. Don't believe I made any changes to them.
https://pastebin.com/ay2WJ2G5

**Comment by angelnc1989** [comment]
Removing the metals I don't have in my pack from the upgrade path, fixes this.

**Comment by HalestormXV** [comment]
I have all the metals in the upgrade path that are listed. I let the mod generate a fresh set of configs and turned off HungryChests and MineCartChests as well as RefinedRelocation Chests just in case.
https://pastebin.com/VU7hsTT9

That is the configs with the update. Crash looks like some type of Malformed Array perhaps during the recipe registration according to the CrashLog which may make sense with all upgrade paths now becoming configurable.

**Comment by Balint66** [comment]
Well, I had the same crash after installing the mod. We share these same mods:  smoothfontcore & smoothfont (renders nicer fonts, shouldn't cause that error), foamfixcore & foamfix, appleskin, blockcraftery, chameleon, Mantle, inspirations, surge and forgelin.

The full crash log is here: https://paste.dimdev.org/wamowizupe.mccrash.

I don't know how does foreach work in java, but I think it is a very interesting crash.
