### ISSUE TITLE
Recipe bug when trying to customise upgrade path

### ISSUE THREAD

**Issue by angelnc1989** [T145/metalchests#71]
## Problem Details
After changing the configs to make the upgrade path Iron -> Silver -> Gold -> Diamond, there is no Silver Chest and the Gold Chest recipe is bugged.
[This](https://pastebin.com/MPSCubjJ) is my config file.
My pack has Copper Ore, but I'm trying to disable it, since no mod uses it. It's added by Erebus.
Silver Ore and Ingots are added by Bewitchment.

## Screenshots
![image](https://user-images.githubusercontent.com/5382585/58763488-bbc0be80-855b-11e9-98b3-bcc4dd906d06.png)

## Environment

- OS: Windows 10
- Full Forge version: 14.23.5.2838
- Mod version: 4.9.2

**Comment by T145** [comment]
This is probably b/c Bewitchment doesn't add Silver to the OreDictionary. MetalChests does all of its material checks through the OreDictionary so it's compatible w/ other mods that add similar ores.

**Comment by T145** [comment]
After browsing the Bewitchment repo ([https://github.com/Um-Mitternacht/Bewitchment](https://github.com/Um-Mitternacht/Bewitchment)) I see no place where anything gets added to the OreDictionary when things get initialized, so I'd go create an issue over there.

**Comment by angelnc1989** [comment]
Bewitchments Silver Ingot is definitly registered as ingotSilver

**Comment by T145** [comment]
Try using v4.9.5. In my test environment everything works perfectly.

![image](https://i.imgur.com/ngN61Nb.png)
