### ISSUE TITLE
Crash after opening the silver chest

### ISSUE THREAD

**Issue by WenXin20** [T145/metalchests#72]
## Problem Details
- I got a crash after using an iron to silver chest upgrade item on an iron chest. I got the crash when trying to open the newly upgraded silver chest. I also have Mouse Tweaks installed if it has anything to do with this.

### Detailed logs of the issue:
- [Crash Report](https://gist.github.com/WenXin20/0cd65f1626f7b3c1d7e63f89969fd10a)

## Environment
- Full Forge version:  v14.23.5.2838-1.12.2
- Metal Chests: v4.9.2
- [Mouse Tweaks](https://minecraft.curseforge.com/projects/mouse-tweaks/files/2671937) v2.10

**Comment by T145** [comment]
This happens when upgrading any chest apparently. Should be a quick fix.

**Comment by WenXin20** [comment]
I still get the same crash with that chest when opening it with v4.9.5

**Comment by T145** [comment]
Well this version fixes everything on my end. Did you change anything in the config file? Are there any mods in that pack you know of that would be edit inventory handlers?

**Comment by WenXin20** [comment]
The config file is the same. I think it might have to do with the Mouse Tweaks mod, I think it was mentioned in the log.

**Comment by T145** [comment]
It's mentioned no where in the log. I'll make a test instance using it though.

**Comment by T145** [comment]
I get nothing:
```
Mods:
  MetalChests-v4.9.5+mc1.12.2
  MouseTweaks-2.10-mc1.12.2
```
There has to be some fringe-case conflict w/ one of the random mods you have installed. Just go through a process of elimination; take out everything not essential and progressively add things back in while testing the upgrades. From my end all lights look green.

**Comment by WenXin20** [comment]
Ok, I'll see what I can do. But other metal chests from previous versions that I haven't upgraded yet opens fine. Could that specific chest be corrupted?

**Comment by WenXin20** [comment]
But I do know that I have the mods trash slot, inventory sorter, quark, and item scroller also installed. It will be some time before I can test it to be sure.

**Comment by WenXin20** [comment]
I forgot to say that breaking and then replacing the same chest fixed the crash. Upgrading new chests doesn't crash either. Seems like the data of that chest was corrupted or something.
