### ISSUE TITLE
Desn't work with mekanism copper ingots.

### ISSUE THREAD

**Issue by AssB0ys** [T145/metalchests#77]
## Problem Details

I installed this mod to an instance with mekanism is also installed, all the recipes work, but the copper chest doesn't have a recipe, although mekanism adds its copper ingot to the game.

## Environment

- OS: Windows 10
- Full Forge version: forge-14.23.5.2838
- Mod version: 5.1.2

**Comment by T145** [comment]
This is either due to the mod loading order or when Mekanism registers its ores. If you use MultiMC, the mod order can be manually configured. Just set MetalChests to load any time after all the mods that affect the OreDict. I'm working on the system to manually enable & disable variants.
