### ISSUE TITLE
Items added ignoring the absence of materials

### ISSUE THREAD

**Issue by AssB0ys** [T145/metalchests#78]
## Problem Details

The mod Metal Chests registers silver chest although the silver ingot is not present in the game, no mods in my instance add a silver ingot. The chest doesn't have a recipe hence is only obtainable in creative.

  -- Expected behavior

The mod shouldn't register uncraftable items. Better yet add a configuration option for each item or block in the mod.

## Environment

- OS: Windows 10
- Full Forge version: forge-14.23.5.2838
- Mod version: 5.1.2

**Comment by T145** [comment]
What does your upgrade path in the config file look like? Which mods do you have installed in your pack? May you provide screenshots of the problem?

**Comment by AssB0ys** [comment]
I think the problem might be that mekanism adds silver dusts, shards etc, but it doesn't add silver ore nor ingot.
There's silver chest:
![2019-06-18_20 46 01](https://user-images.githubusercontent.com/49584508/59706944-423af880-920a-11e9-8e8a-23c24d615957.png)
But there is no silver ingot, because none of the mods I have installed add silver ingot, although mekanism for some reason has silver dusts:
![2019-06-18_20 46 09](https://user-images.githubusercontent.com/49584508/59707011-67c80200-920a-11e9-8d9d-0598ccdcdbf2.png)
Mekanism is the only mod in my pack that adds custom metals.

**Comment by T145** [comment]
There's your problem then. Mekanism is adding `ingotSilver` to the OreDict, making MetalChests think the ingot is registered, but b/c Mekanism doesn't add the ingot the recipe doesn't get updated. Just add a mod like Thermal Foundation and your problems should be fixed.

**Comment by AssB0ys** [comment]
Hello, can you reopen this and look into this issue one more time? Mekanism mod doesn't actually register the oredict item as stated here https://github.com/mekanism/Mekanism/issues/5524#issuecomment-503805162 - a check must be initiated to check if an oredictionary entry is an _empty list_.
