### ISSUE TITLE
Crystal chest does not render until highlighted by looking at.

### ISSUE THREAD

**Issue by rallias** [T145/metalchests#8]
When I load a world with crystal chests, they are invisible until I hover over them with the player looking thingy.

### Expected Behavior

Crystal chests should always be visible.

### Actual Behavior

Note that the first crystal chests I'd already looked at before taking screenshot. Both existed at world load though.

![2018-07-04_19 46 36](https://user-images.githubusercontent.com/1843506/42297193-418656fa-7fc3-11e8-8588-a2978135a3b5.png)
![2018-07-04_19 46 41](https://user-images.githubusercontent.com/1843506/42297194-4197f70c-7fc3-11e8-96d6-825c979eb2af.png)

### Steps to Reproduce (including precondition)

1. Place crystal chest.
2. Close world.
3. Re-open world.

### Screenshot of this Problem

![2018-07-04_19 46 36](https://user-images.githubusercontent.com/1843506/42297193-418656fa-7fc3-11e8-8588-a2978135a3b5.png)
![2018-07-04_19 46 41](https://user-images.githubusercontent.com/1843506/42297194-4197f70c-7fc3-11e8-96d6-825c979eb2af.png)

### Your Environment

- OS: Windows 8.1
- Full Forge version: 1.12.2-14.23.4.2727
- Mod version: 1.2.2

**Comment by T145** [comment]
This Crystal variant is being removed. Mainly because it breaks a lot of the progressive & intuitive upgrade progressions that are going to come later in the mod.
