### ISSUE TITLE
OreDict recipe conflict

### ISSUE THREAD

**Issue by KokSaker** [T145/metalchests#81]
## Problem Details
I have two mods installed that add their own versions of metals. Mekanism and Immersive engineering. There are two kinds copper ingots in my game and one kind of silver ingot. Neither of them are used in crafting a corresponding chest - the copper and silver chest don't have any recipes. And corresponding upgrades are not even showing up in JEI.

See on the right side - no copper or silver upgrades:
![2019-06-29_23 12 01](https://user-images.githubusercontent.com/52161081/60389066-d5eead80-9ac3-11e9-9d4b-9c07943c1cc6.png)
although copper and silver chests are present(without recipes - uncraftable).
  -- Expected behavior
Chests should use oreDict entries in their recipes. Also there should be silver and copper upgrades.

  -- Detailed logs of the issue -->
there are no errors in the log or anything related to metal chests mod.
## Environment

- OS: Windows 10 x64
- Full Forge version: 14.23.5.2838
- Mod version: 5.2.8+mc1.12.2

**Comment by T145** [comment]
Have you changed the upgrade path at all?

**Comment by KokSaker** [comment]
I didn't touch any configurations
`
    # The upgrade path for metal chests. Recipes will update to reflect this.
    #  Current valid options are: { "copper", "iron", "silver", "gold", "diamond", "obsidian" }
    S:upgradePath <
        copper
        iron
        silver
        gold
        diamond
        obsidian
     >`
It's like this.

**Comment by KokSaker** [comment]
I just checked the ironChests mod in the copy of an instance and it recognizes the copper and silver ingots I have.

**Comment by T145** [comment]
When I load a test instance w/ just these mods installed I don't get the copper and silver chests added at all. A similar issue popped up in the past regarding Mekanism & load order that was resolved, so I'm not sure what's causing this right away.

**Comment by T145** [comment]
I think this should be an easy fix. May take a little bit since I need to back up my work on custom GUIs & fix my dang CF page after Curse broke it.

**Comment by KokSaker** [comment]
Thanks for looking into this. Tell me if you need me to do additional testing or gather information.
