### ISSUE TITLE
GUI inconsistency to vanilla chest

### ISSUE THREAD

**Issue by KokSaker** [T145/metalchests#82]
## Problem Details
There is a minor issue with the Metal Chests GUI textures.
1. The inset from the sides is a little bit too thick, compared to vanilla chest.
2. The chest title is missing - although this could actually be omitted for bigger chests, but better if it was configurable.
## Screenshots
![2019-06-29_23 12 10](https://user-images.githubusercontent.com/52161081/60389110-d76ca580-9ac4-11e9-9e56-d288006e24e0.png)
![2019-06-29_23 12 14](https://user-images.githubusercontent.com/52161081/60389111-d76ca580-9ac4-11e9-9df8-76a134386a83.png)

## Environment
- OS: Windows 10 x64
- Full Forge version: 14.23.5.2838
- Mod version: 5.2.8+mc1.12.2

**Comment by T145** [comment]
The GUI textures were taken directly from IronChests. They should be changed in the next significant version.

**Comment by KokSaker** [comment]
Just wanted to say that the new GUI textures are GREAT! Thank you!
