### ISSUE TITLE
[CRASH] Conflict w/ InventoryTweaks

### ISSUE THREAD

**Issue by angelnc1989** [T145/metalchests#83]
## Problem Details
Game crashes when opening Iron Chest

https://pastebin.com/dtCjrzbg

## Environment

- OS: Windows 10 64-bit
- Full Forge version: 14.23.5.2838
- Mod version: 5.5.0

**Comment by T145** [comment]
Does this happen when sorting using InvTweaks?

**Comment by angelnc1989** [comment]
I just opened the chest. Couldn't do anything else.
