### ISSUE TITLE
[Bug] Placing enchanted chests on server crashes player

### ISSUE THREAD

**Issue by Akitori** [T145/metalchests#85]
## Problem Details
There is a server issue where placing a enchanted chest randomly crashes the placer.

1. Get enchanted chest.
2. Place it down once. Open it, look inside, notice slots aren't added.
3. Try to replace chest.
4. CRAAASSSSSHHH

https://pastebin.com/BiU5wKXG

## Environment

- OS: Windows 10
- Full Forge version: forge1.12.2-14.23.5.2838
- Mod version: MetalChests 5.2.8

**Comment by T145** [comment]
This seems to be happening b/c an instance of the Obsidian chest cannot be read from the tile entity NBT. You say this is happening w/ an iron chest? Have you changed the mod's JSON config file at all?

**Comment by Akitori** [comment]
I haven't changed any files related to Iron Chest, so i will safely say no.

**Comment by T145** [comment]
So when you say "Iron Chest" do you mean any metal chest?

**Comment by Akitori** [comment]
Yes, any enchanted chest.

**Comment by Akitori** [comment]
Also some strange things server side. After the chest is placed, when relogging back in, the chest is facing away from the player and lacks the enchanted glint. Its just a normal iron chest at that point

**Comment by T145** [comment]
After some minor changes, I see no crashing from interacting w/ an enchanted chest, even after restarting the server. Something small likely fixed this.
