### ISSUE TITLE
Quark Chest Buttons don't work

### ISSUE THREAD

**Issue by angelnc1989** [T145/metalchests#86]
## Problem Details
The buttons Quark adds on the side of chest GUIs worked with the previous versions of Metal Chests and now they aren't there on any Metal Chests GUI.

## Environment

- OS: Windows 10 64-bit
- Full Forge version: 14.23.5.2838
- Mod version: 5.5.3

**Comment by T145** [comment]
Think these were accidentally disabled while I was messing w/ the interactions btwn. Quark and InventoryTweaks. It should be a quick fix when I have the time.
