### ISSUE TITLE
[Error] Server startup ugly

### ISSUE THREAD

**Issue by JoshOOOOWAH** [T145/metalchests#87]
## Problem Details

When server started i catch that error

Thats dont crash, just error but look ugly

https://pastebin.com/zzHBCfnC

ModList:
https://pastebin.com/kfqFW4fW

_I am using [ServerWrapper](github.com/GravitLauncher/Launcher) if thats important _

## Environment

- OS: Windows
- Full Forge version: forge-1.12.2-14.23.5.2825
- Mod version: v5.5.3

**Comment by T145** [comment]
Well, in this context, #85 begins to make more sense. I'll look into it.
