### ISSUE TITLE
[Feature] Have chests say their type inside the inventory by default

### ISSUE THREAD

**Issue by IronPiston** [T145/metalchests#89]
Currently, chests just say "Chest" at the top. Could this be changed to have their material type be included as well (like "Copper Chest" or "Iron Chest")? Currently, you have to enchant a chest to have it have the material in the name.

**Comment by T145** [comment]
As you know, this is how it used to be. I have it how it is presently b/c some of the names intersect w/ the Quark search bar. I'd like to set the Quark search bar to always be at the top of the player's inventory, but presently have not been able to do so.
