### ISSUE TITLE
Adjusting chest dimensions leads to green texture

### ISSUE THREAD

**Issue by IronPiston** [T145/metalchests#90]
## Problem Details
Changing the dimensions of chests leads to a green texture. The actual size is correct, but the GUI is rendering incorrectly

## Environment

- OS: Fedora 30
- Full Forge version: 1.12.2 - 14.23.5.2838
- Mod version: 5.5.3

![2019-07-06_17 26 00](https://user-images.githubusercontent.com/11603684/60761692-658be300-a013-11e9-8f70-b0e57386e0c4.png)

**Comment by T145** [comment]
You can't have more than 6 rows as of now. Hopefully @TimGnoll can resize the GUI image, allowing for larger custom chest sizes.

**Comment by IdrisQe** [comment]
Currently, it seems more than 8 rows is not supported.
![image](https://user-images.githubusercontent.com/40530630/65727714-5f832c80-e06d-11e9-8234-68265f67dd59.png)

While it may be difficult and require some funky UI positional work, it may be worth it to cut the whole UI texture into modular segments that are loaded in a specific order based on the config size setting (assuming this is possible)
I'd do it like this:
TopLeft, Top, TopRight
Left, Slot, Right
BottomLeft, Bottom, BottomRight
then just duplicate as needed.
want a 9 rows x 12 columns chest?
Render in order, positionally:
1x: TL, Tx12, TR
9x: L, Sx12, R
1x: BL, Bx12, BR

A simple 2 rows x 2 rows chest?
1x: TL, Tx2, TR
2x: L, Sx2, R
1x: BL, Bx2, BR
EG:
![cutup](https://user-images.githubusercontent.com/40530630/65728689-8b53e180-e070-11e9-9a07-226062e70108.png)
(granted, a 2x2 wouldn't have enough space for the name, but you could always set a minimum size requirement)

**Comment by T145** [comment]
@IdrisQe Read the comments: https://github.com/T145/metalchests/blob/master/src/main/java/t145/metalchests/core/MetalChests.java#L130

**Comment by IdrisQe** [comment]
I... I know.
I did see the comments.
I just don't understand the seemingly-arbitrary limit and was reccommending a way to get around it (although my modding knowledge is limited).
