### ISSUE TITLE
Crash on startup - Client

### ISSUE THREAD

**Issue by Danymaddox** [T145/metalchests#93]
## Problem Details

 https://pastebin.com/JuPBktS2

## Environment

-   OS: 
-   Full Forge version: 
-   Mod version:

**Comment by T145** [comment]
Read here: [https://www.curseforge.com/minecraft/mc-mods/tbone](https://www.curseforge.com/minecraft/mc-mods/tbone)

**Comment by duely** [comment]
Please keep this open somewhere so it's easily visible. I just had to do a binary search through an extremely large mod pack just to work out which mod (or set of mods) was causing the error in the first place, which resulted in at least 2 hours of launching and relaunching the pack. I checked here first, then CurseForge, and was despairing I had to remove this mod until I saw this issue.
