### ISSUE TITLE
[Question] Updating from v4.0.1

### ISSUE THREAD

**Issue by knoxhack** [T145/metalchests#96]
Is there a way to update the mod from MetalChests-v4.0.1.g01955d6 to newest versions without deleting all inventories?

**Comment by knoxhack** [comment]
MetalChests-v4.0.1.g01955d6 got removed from CurseForge now Im not longer able to update my modpack because of it :( Modpack: Mystical Skies

**Comment by T145** [comment]
If you update the mod to the latest version, your worlds should be just fine. However, if you try to open the chests, you'll crash. The inventory items will still persist though, so all that's needed is for users to break the chests and replace them. That'll just need to be a PSA in the pack changelog.

**Comment by knoxhack** [comment]
If that's the case I'm not sure why version v4.0.1 got removed from CurseForge, I had no problems with it and updating it this way and making the user crash their client and replace all chest is not the best solution

**Comment by knoxhack** [comment]
Last time I tried to update to a newer version than v4.0.1 a chest and Inventories got deleted

**Comment by knoxhack** [comment]
You should have at least left the v4 version available for modpacks marker that don't want to break modpack updates because I don't really want to update with all these side effects and crashes

**Comment by T145** [comment]
I've restored the version for the time being. I'd prefer that all pack makers go to the latest version, b/c it has some significant optimizations and customization options over the older versions. I'll look into how to handle updating significantly changed tiles in-world so this doesn't have to be an issue later.

**Comment by T145** [comment]
@knoxhack Do you have a Discord, and if so may you join and test a development build to see if porting from older versions is seemless?

**Comment by knoxhack** [comment]
Thanks a lot for restoring it, I wanted to push an important small update for my modpack and then work on a more unstable beta version. 
And yeah I interested on helping out test newer builds for future updates.
I'm on discord: knoxhack#2547

**Comment by T145** [comment]
My discord server is here: https://discord.gg/3a3RW7H

**Comment by T145** [comment]
Try out this latest release and see if it solves your update problems. It fixed everything for me.
