### ISSUE TITLE
Gold to Silver Chest Upgrade Shrinks Chest Size

### ISSUE THREAD

**Issue by WenXin20** [T145/metalchests#98]
## Problem Details

- Upgrading my gold chest using the Gold to Silver Upgrade shrunk the amount of chest slots. Gold had 80, but the silver has 72. 
- Nothing was changed in the config file. 

## Environment

-   Full Forge version:  v14.23.5.2838
-   Mod version:  v5.8.9

**Comment by T145** [comment]
You need to change the chest sizes manually. In the config file, simply swap the number of rows and columns for each type.

**Comment by WenXin20** [comment]
Shouldn't it, by default, be bigger without having to change the config?

**Comment by T145** [comment]
No, b/c then you wouldn't have complete control over customization.

**Comment by WenXin20** [comment]
Ok, though I was unaware it was a smaller size before upgrading my chest, because I had never looked at the config file before today.

**Comment by WenXin20** [comment]
From what I remember, didn't the silver chest use to be bigger than gold? But now it's smaller, but there is still a Gold to Silver Upgrade item. Shouldn't it be a silver to gold item upgrade instead?

**Comment by T145** [comment]
No, it has never been that way. https://github.com/T145/metalchests/blob/0d4b68ff1d14fa911e74d90203bd8c0213b26d79/src/main/java/T145/metalchests/api/immutable/ChestType.java#L35

**Comment by WenXin20** [comment]
Huh, I guess it has been. Just seemed odd to me.

**Comment by NullMagic** [comment]
Not to reopen an old issue, but is the gold chest meant to upgrade to the silver chest? I know in the pictures it shows the gold chest as being an upgrade to the silver chest, but in game it shows silver as being an upgrade to gold, is this intended?
